version: "3.9"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pacifico
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8087:8080
    networks:
      - app_network

networks:
  app_network: